# Generated by Django 2.2.4 on 2019-10-10 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='email_token',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='verification',
            name='phone_token',
            field=models.CharField(max_length=255),
        ),
    ]
