# Generated by Django 2.2.4 on 2019-08-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='msg_type',
            field=models.CharField(default='TEXT', max_length=11),
        ),
    ]
