# Generated by Django 2.2.4 on 2020-02-28 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_delieveryreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=13)),
                ('msg_id', models.CharField(max_length=255)),
                ('response_code', models.CharField(max_length=25)),
                ('status', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('ACKED', 'Aknowledge'), ('ENROUTE', 'Enroute'), ('DELIVRD', 'Delivered'), ('EXPIRED', 'Expired'), ('DELETED', 'Deleted'), ('UNDELIV', 'Undelivered'), ('ACCEPTED', 'Accepted'), ('REJECTD', 'Rejected')], default='SENT', max_length=255)),
                ('cost_sms', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('charge', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('MCC_MNC', models.CharField(max_length=25)),
                ('error_code', models.CharField(max_length=25)),
                ('tag_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Message')),
            ],
        ),
        migrations.DeleteModel(
            name='DelieveryReport',
        ),
    ]
